# Generated by Django 5.2.3 on 2025-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='word_template',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='kundalik_template',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='shartnoma_template',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='yollanma_template',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
